### PR TITLE
Merge Clang LLVM 3.6.2 changes into SPIR

### PR DESCRIPTION
**Pull request by InBetweenNames**
This PR is to prepare for future work in porting the OpenCL C and OpenCL C++ compiler work to LLVM 3.8. This brings the repository up to date with release_36 in the official LLVM Clang repository.  All tests pass.

### CODE REVIEW

**Comment by Trass3r** [comment]
Readme claims it's already on 3.6?

**Comment by InBetweenNames** [comment]
It's slightly behind, unfortunately.  The readme indicates that it is not up to 3.6.2 yet.   This patch brings us there for a future 3.8 merge

**Comment by Trass3r** [comment]
Hopefully merged soon then! :)

**Comment by yxsamliu** [comment]
Do lit tests pass with this merge?

Thanks.

**Comment by InBetweenNames** [comment]
Yup, all of them pass

**Comment by Trass3r** [comment]
I really wonder why this gets ignored.

**Comment by bader** [comment]
We had an offline discussion with Shane about this patch and my biggest concern is that it not clear how it helps with the final goal: porting OpenCL C/C++ compiler(s) to LLVM 3.8 infrastructure.

I see two options:
1. Merge LLVM 3.8 release branch to spirv-1.1. Since merge base is the latest common commit for both branches and LLVM community accepts commits to release branch _only_ from the trunk, there will be conflict for each commit in this pull request (which potentially might be automatically resovled by GIT).
2. Rebase spirv-1.1 branch on top of LLVM 3.8 release branch. This pull request will be just dropped in the scenario, since all these commits already applied to LLVM 3.8 release branch.

What is the strategy to move both compiler(s) (i.e. spirv-1.0 and spirv-1.1 branches) to LLVM 3.8?

**Comment by InBetweenNames** [comment]
Indeed--Alexey is right on point.  I had already tried previously to use strategy 1 and I had a very difficult time--git imerge helped, but after about a week of the imerge running I had to stop it in order to move on to other tasks.  I also tried strategy 2, but Clang had changed significantly, making the rebase just as difficult.  In particular, debug info changed between 3.6 and 3.7.  Also, there exists an incompatible OpenCL C frontend in Clang 3.8 as well, making things even murkier.  To my knowledge, OpenCL C++ has not been implemented in Clang master yet.

I was able to successfully merge SPIRV-LLVM with LLVM 3.8 however.  That work can be found in the SPIRV-LLVM repo, and it was agreed that future work will be on that new branch.

I hope someone else has more success with merging SPIR with Clang 3.8 (or, better yet, 3.9 or master now).

The purpose of this PR was to hopefully set things up to make such a merge easier, but such an invasive change is required that I'm not sure if accepting it would help at this point.  For further discussion, it may be worthwhile to create an issue and use that as the discussion point instead of this PR, and close this PR.  Your thoughts?

-Shane

**Comment by bader** [comment]
No objections from my side.
FWIW, most of the OpenCL C functionality is already supported by Clang 3.9.

**Comment by InBetweenNames** [comment]
That's good to know!

Closing this PR -- discussion can continue on this issue here:

https://github.com/KhronosGroup/SPIR/issues/56

**Pull request closed without merging**
