### PR TITLE
Remove convert_{float|double|half}*_sat* functions from opencl-20.h s…

### PR DESCRIPTION
**Pull request by yxsamliu**
…ince they are invalid.

The _sat modifier may not be used for conversions to floating-point formats.

opencl-12.h does not contain such functions.

### CODE REVIEW

**Comment by bader** [comment]
Sam, you pushed one more commit (b7449ec53339a161918d7c59606ad3260ffb171e) to 'header4' branch after pull request was created, so accidentally merged it too.

**Comment by yxsamliu** [comment]
sorry. I should have updated the title. Can you take a look if it is OK? If not we can revert it. Thanks.

**Comment by bader** [comment]
The change looks good to me. I just wanted to let you know that I merged this change.
I also noticed that you added a macro:
#define __readonly __attribute__((pure))
but I can't find where it's used. Are you going to apply it later?

**Comment by yxsamliu** [comment]
This __readonly is in opencl-12.h, so I copied it to opencl-20.h. It is not used in either opencl-12.h and opencl-20.h. Do you think it should be removed?

**Comment by bader** [comment]
I think so. I guess there should be a couple of functions that might be marked with 'pure' attribute, but I most of the built-ins should go with more strict 'const' attribute.

**Comment by yxsamliu** [comment]
OK I will remove it. Thanks.

**Pull request merged**
