### PR TITLE
Merge opencl-12.h and opencl-20.h as opencl.h

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by bader** [comment]
#ifdef cl_khr_fp16
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
typedef half half2 **attribute**((ext_vector_type(2)));
typedef half half3 **attribute**((ext_vector_type(3)));
typedef half half4 **attribute**((ext_vector_type(4)));
typedef half half8 **attribute**((ext_vector_type(8)));
typedef half half16 **attribute**((ext_vector_type(16)));
#endif

I don't think it's right think to do since user will not be able to use pointers to half vector types without enabling cl_khr_fp16.

**Comment by bader** [comment]
#define NULL                              0

This macro is not defined in OpenCL C language. In C99 it's defined in stddef.h file. So I don't think it should be defined by default.

**Comment by bader** [comment]
float **attribute**((overloadable)) fract(float x, __global float *iptr);
in opencl-12.h is moved with definitions of 'double' variants. Could you return it back to 'float' versions, please?
The same for frexp, lgamma_r, modf, remquo, sincos.

**Comment by bader** [comment]
Original order to built-in functions in opencl-12.h matched the order from the specification. Could we try to preserve it? Particularly I noticed that synchronization functions were uplifted right after relational functions.

**Comment by yxsamliu** [comment]
#ifdef cl_khr_fp16
#pragma OPENCL EXTENSION cl_khr_fp16 : enable
typedef half half2 attribute((ext_vector_type(2)));
typedef half half3 attribute((ext_vector_type(3)));
typedef half half4 attribute((ext_vector_type(4)));
typedef half half8 attribute((ext_vector_type(8)));
typedef half half16 attribute((ext_vector_type(16)));
#endif

According to the spec and extension spec, vector half type is only available when cl_khr_fp16 is enabled. Users should not use vector half pointer type when cl_khr_fp16 is not enabled.

**Comment by yxsamliu** [comment]
About NULL:
opencl 1.2 does not define it, but OpenCL 2.0 s6.10 defines it, so I will remove it from opencl-12.h but keep it in opencl-20.h.

**Comment by bader** [comment]
You are right about vector half types.
Does it make sense to create a new header with shared functionality and move functionality there in manageable manner? The diff here is huge. It's difficult to track if some built-in function were move or removed from the header (I noticed a couple of cases).

**Comment by yxsamliu** [comment]
Yes I can create opencl-common.h and move the common parts to it.

**Comment by yxsamliu** [comment]
About the layout of the header files, my original plan is:

common part
opencl1.2 specific part
opencl2.0 specific part

However, the builtin functions will not follow the order of the spec, so I would like to follow your suggestion to keep the builtin functions in the order of the spec. This will result in more conditional macros but I think it more readable.

**Comment by yxsamliu** [comment]
I think better to do more discussion about the layout at http://reviews.llvm.org/D18369

**Comment by bader** [comment]
No problem. Following the spec. order allowed me to check if all of the functions from the spec. is in the header or not. I also created a little bit of сhaos in opencl-12.h with half extension by adding missing built-ins to the end of file.

Feel free to change the order if new one will be easy to digest. :-)

**Comment by yxsamliu** [comment]
I have merged opencl-12.h and opencl-20.h to opencl.h. Please take a look. Thanks.

**Comment by bader** [comment]
Sam, could you also update lib/Headers/CMakeLists.txt, so this header will be copied during installation and update README.md file in the root directory, please?

**Comment by yxsamliu** [comment]
Updated cmake file and README.md to use opencl.h.

**Comment by yxsamliu** [comment]
Updated with Alexey's patches.

**Comment by bader** [comment]
LGTM.
Are you okay if we squash commits in 'header4' branch with merging?

**Comment by yxsamliu** [comment]
This one contains merges and cannot be squashed. I will open another pull request.

**Pull request closed without merging**
